["LADM_COL_V3_0.LADM_Nucleo.col_puntoReferencia.ue"]
hidden="True"

["LADM_COL_V3_0.LADM_Nucleo.COL_UnidadEspacial.Ext_Direccion_ID"]
hidden="True"

["LADM_COL_V3_0.LADM_Nucleo.ExtUnidadEdificacionFisica.Ext_Direccion_ID"]
hidden="True"

["LADM_COL_V3_0.LADM_Nucleo.ExtInteresado.Ext_Direccion_ID"]
hidden="True"

# ExtDireccion

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Clase_Via_Principal"]
form_order=4

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Codigo_Postal"]
form_order=3

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Complemento"]
form_order=12

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Es_Direccion_Principal"]
form_order=2

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Letra_Via_Generadora"]
form_order=9

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Letra_Via_Principal"]
form_order=6

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Localizacion"]
form_order=14

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Nombre_Predio"]
form_order=13

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Numero_Predio"]
form_order=10

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Sector_Ciudad"]
form_order=7

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Sector_Predio"]
form_order=11

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Tipo_Direccion"]
form_order=1

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Valor_Via_Generadora"]
form_order=8

["LADM_COL_V3_0.LADM_Nucleo.ExtDireccion.Valor_Via_Principal"]
form_order=5

# LC_Predio

["LADM_COL_V3_0.LADM_Nucleo.COL_UnidadAdministrativaBasica.Nombre"]
form_order=14

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Predio.Avaluo_Catastral"]
form_order=13

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Predio.Codigo_ORIP"]
form_order=4

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Predio.Condicion_Predio"]
form_order=12

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Predio.Departamento"]
form_order=1

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Predio.Direccion"]
form_order=10

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Predio.Id_Operacion"]
form_order=9

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Predio.Matricula_Inmobiliaria"]
form_order=5

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Predio.Municipio"]
form_order=2

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Predio.NUPRE"]
form_order=8 

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Predio.Numero_Predial"]
form_order=6

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Predio.Numero_Predial_Anterior"]
form_order=7

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Predio.Tiene_FMI"]
form_order=3

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Predio.Tipo"]
form_order=11

# LC_DatosAdicionalesLevantamientoCatastral

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.lc_informacion_adicional_predio.lc_predio"]
form_order=19

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_DatosAdicionalesLevantamientoCatastral.Area_Registral_M2"]
form_order=5

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_DatosAdicionalesLevantamientoCatastral.Categoria_Suelo"]
form_order=3

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_DatosAdicionalesLevantamientoCatastral.Clase_Suelo"]
form_order=2

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_DatosAdicionalesLevantamientoCatastral.Destinacion_Economica"]
form_order=1

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_DatosAdicionalesLevantamientoCatastral.Fecha_Visita_predial"]
form_order=9

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_DatosAdicionalesLevantamientoCatastral.Novedad_FMI"]
form_order=8

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_DatosAdicionalesLevantamientoCatastral.Novedad_Numeros_Prediales"]
form_order=7

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_DatosAdicionalesLevantamientoCatastral.Numero_Documento_Reconocedor"]
form_order=14

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_DatosAdicionalesLevantamientoCatastral.Observaciones"]
form_order=12

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_DatosAdicionalesLevantamientoCatastral.Primer_Apellido_Reconocedor"]
form_order=17

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_DatosAdicionalesLevantamientoCatastral.Primer_Nombre_Reconocedor"]
form_order=15

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_DatosAdicionalesLevantamientoCatastral.Procedimiento_Catastral_Registral"]
form_order=6

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_DatosAdicionalesLevantamientoCatastral.Resultado_Visita"]
form_order=10

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_DatosAdicionalesLevantamientoCatastral.Segundo_Apellido_Reconocedor"]
form_order=18

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_DatosAdicionalesLevantamientoCatastral.Segundo_Nombre_Reconocedor"]
form_order=16

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_DatosAdicionalesLevantamientoCatastral.Suscribe_Acta_Colindancia"]
form_order=11

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_DatosAdicionalesLevantamientoCatastral.Tiene_Area_Registral"]
form_order=4

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_DatosAdicionalesLevantamientoCatastral.Tipo_Documento_Reconocedor"]
form_order=13

# LC_OfertasMercadoInmobiliario

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.lc_predio_ofertas_mercado_inmobiliario.lc_predio"]
form_order=8

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_OfertasMercadoInmobiliario.Fecha_Captura_Oferta"]
form_order=4

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_OfertasMercadoInmobiliario.Nombre_Oferente"]
form_order=6

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_OfertasMercadoInmobiliario.Numero_Contacto_Oferente"]
form_order=7

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_OfertasMercadoInmobiliario.Tiempo_Oferta_Mercado"]
form_order=5

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_OfertasMercadoInmobiliario.Tipo_Oferta"]
form_order=1

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_OfertasMercadoInmobiliario.Valor_Negociado"]
form_order=3

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_OfertasMercadoInmobiliario.Valor_Pedido"]
form_order=2

# LC_ContactoVisita

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.lc_informacion_adicional_contacto.lc_datos_adicionales"]
form_order=12

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_ContactoVisita.Autoriza_Notificaciones"]
form_order=10

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_ContactoVisita.Celular"]
form_order=9

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_ContactoVisita.Correo_Electronico"]
form_order=8

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_ContactoVisita.Domicilio_Notificaciones"]
form_order=11

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_ContactoVisita.Numero_Documento_Quien_Atendio"]
form_order=2

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_ContactoVisita.Primer_Apellido_Quien_Atendio"]
form_order=5

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_ContactoVisita.Primer_Nombre_Quien_Atendio"]
form_order=3

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_ContactoVisita.Relacion_Con_Predio"]
form_order=7

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_ContactoVisita.Segundo_Apellido_Quien_Atendio"]
form_order=6

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_ContactoVisita.Segundo_Nombre_Quien_Atendio"]
form_order=4

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_ContactoVisita.Tipo_Documento_Quien_Atendio"]
form_order=1

# LC_Interesado

["LADM_COL_V3_0.LADM_Nucleo.COL_Interesado.Nombre"]
form_order=11

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Interesado.Documento_Identidad"]
form_order=3

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Interesado.Grupo_Etnico"]
form_order=9

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Interesado.Primer_Apellido"]
form_order=6

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Interesado.Primer_Nombre"]
form_order=4

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Interesado.Razon_Social"]
form_order=10

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Interesado.Segundo_Apellido"]
form_order=7

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Interesado.Segundo_Nombre"]
form_order=5

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Interesado.Sexo"]
form_order=8

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Interesado.Tipo"]
form_order=1

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Interesado.Tipo_Documento"]
form_order=2

# LC_Derecho

["LADM_COL_V3_0.LADM_Nucleo.col_baunitRrr.unidad"]
form_order=5

["LADM_COL_V3_0.LADM_Nucleo.col_rrrInteresado.interesado"]
form_order=6

["LADM_COL_V3_0.LADM_Nucleo.COL_DRR.Descripcion"]
form_order=4

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Derecho.Fecha_Inicio_Tenencia"]
form_order=2

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Derecho.Fraccion_Derecho"]
form_order=3

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Derecho.Tipo"]
form_order=1

# LC_Restriccion

["LADM_COL_V3_0.LADM_Nucleo.col_baunitRrr.unidad"]
form_order=3

["LADM_COL_V3_0.LADM_Nucleo.col_rrrInteresado.interesado"]
form_order=4

["LADM_COL_V3_0.LADM_Nucleo.COL_DRR.Descripcion"]
form_order=2

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Restriccion.Tipo"]
form_order=1

# LC_UnidadConstruccion

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.lc_construccion_unidadconstruccion.lc_construccion"]
form_order=25

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_UnidadConstruccion.Altura"]
form_order=15

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_UnidadConstruccion.Anio_Construccion"]
form_order=12

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_UnidadConstruccion.Area_Construida"]
form_order=13

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_UnidadConstruccion.Area_Privada_Construida"]
form_order=14

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_UnidadConstruccion.Avaluo_Unidad_Construccion"]
form_order=16

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_UnidadConstruccion.Identificador"]
form_order=1

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_UnidadConstruccion.Observaciones"]
form_order=17

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_UnidadConstruccion.Planta_Ubicacion"]
form_order=4

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_UnidadConstruccion.Tipo_Construccion"]
form_order=5

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_UnidadConstruccion.Tipo_Dominio"]
form_order=6

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_UnidadConstruccion.Tipo_Planta"]
form_order=3

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_UnidadConstruccion.Tipo_Unidad_Construccion"]
form_order=2

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_UnidadConstruccion.Total_Banios"]
form_order=10

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_UnidadConstruccion.Total_Habitaciones"]
form_order=9

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_UnidadConstruccion.Total_Locales"]
form_order=11

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_UnidadConstruccion.Total_Pisos"]
form_order=8

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_UnidadConstruccion.Uso"]
form_order=7

# LC_Construccion

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Construccion.Altura"]
form_order=10

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Construccion.Anio_Construccion"]
form_order=8

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Construccion.Area_Construccion"]
form_order=9

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Construccion.Avaluo_Construccion"]
form_order=11

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Construccion.Identificador"]
form_order=1

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Construccion.Numero_Mezanines"]
form_order=7

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Construccion.Numero_Pisos"]
form_order=4

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Construccion.Numero_Semisotanos"]
form_order=6

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Construccion.Numero_Sotanos"]
form_order=5

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Construccion.Observaciones"]
form_order=12

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Construccion.Tipo_Construccion"]
form_order=2

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Construccion.Tipo_Dominio"]
form_order=3

# LC_Terreno

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Terreno.Area_Terreno"]
form_order=1

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Terreno.Avaluo_Terreno"]
form_order=2

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Terreno.Geometria"]
form_order=4

["Modelo_Aplicacion_LADMCOL_Lev_Cat_V1_1.Levantamiento_Catastral.LC_Terreno.Manzana_Vereda_Codigo"]
form_order=3

# Common fields

["LADM_COL_V3_0.LADM_Nucleo.COL_UnidadEspacial.Dimension"]
form_order=898

["LADM_COL_V3_0.LADM_Nucleo.COL_UnidadEspacial.Etiqueta"]
form_order=899

["LADM_COL_V3_0.LADM_Nucleo.COL_UnidadEspacial.Relacion_Superficie"]
form_order=900

["LADM_COL_V3_0.LADM_Nucleo.ObjetoVersionado.Comienzo_Vida_Util_Version"]
form_order=901

["LADM_COL_V3_0.LADM_Nucleo.ObjetoVersionado.Fin_Vida_Util_Version"]
form_order=902

["LADM_COL_V3_0.LADM_Nucleo.Oid.Espacio_De_Nombres"]
form_order=903

["LADM_COL_V3_0.LADM_Nucleo.Oid.Local_Id"]
form_order=904